/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CallPeerIdRouteImport } from './routes/call.$peerId'
import { Route as ChatPeerIdRouteImport } from './routes/chat.$peerId'
import { Route as PersonIdRouteImport } from './routes/person.$id'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CallPeerIdRoute = CallPeerIdRouteImport.update({
  id: '/call/$peerId',
  path: '/call/$peerId',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatPeerIdRoute = ChatPeerIdRouteImport.update({
  id: '/chat/$peerId',
  path: '/chat/$peerId',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonIdRoute = PersonIdRouteImport.update({
  id: '/person/$id',
  path: '/person/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/call/$peerId': typeof CallPeerIdRoute
  '/chat/$peerId': typeof ChatPeerIdRoute
  '/person/$id': typeof PersonIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/call/$peerId': typeof CallPeerIdRoute
  '/chat/$peerId': typeof ChatPeerIdRoute
  '/person/$id': typeof PersonIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/call/$peerId': typeof CallPeerIdRoute
  '/chat/$peerId': typeof ChatPeerIdRoute
  '/person/$id': typeof PersonIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/call/$peerId'
    | '/chat/$peerId'
    | '/person/$id'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/call/$peerId'
    | '/chat/$peerId'
    | '/person/$id'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/call/$peerId'
    | '/chat/$peerId'
    | '/person/$id'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  CallPeerIdRoute: typeof CallPeerIdRoute
  ChatPeerIdRoute: typeof ChatPeerIdRoute
  PersonIdRoute: typeof PersonIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/call/$peerId': {
      id: '/call/$peerId'
      path: '/call/$peerId'
      fullPath: '/call/$peerId'
      preLoaderRoute: typeof CallPeerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/$peerId': {
      id: '/chat/$peerId'
      path: '/chat/$peerId'
      fullPath: '/chat/$peerId'
      preLoaderRoute: typeof ChatPeerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/person/$id': {
      id: '/person/$id'
      path: '/person/$id'
      fullPath: '/person/$id'
      preLoaderRoute: typeof PersonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  CallPeerIdRoute: CallPeerIdRoute,
  ChatPeerIdRoute: ChatPeerIdRoute,
  PersonIdRoute: PersonIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
